const translations = {
  en: {
    loginTitle: 'Make smarter purchasing decisions with data-driven demand forecasting.',
    loginKicker: 'Welcome back',
    signInTitle: 'Sign in',
    usernameLabel: 'Username or email',
    passwordLabel: 'Password',
    rememberMe: 'Remember me',
    loginButton: 'Login',
    demoAccount: 'Demo Account',
    tagline: 'Smart Vegetable Waste Reduction',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    sales: 'Sales',
    forecast: 'Forecast',
    recommendations: 'Recommendations',
    waste: 'Waste',
    reports: 'Reports',
    settings: 'Settings',
    prototypeVersion: 'Prototype Version 0.1',
    prototypeNote: 'Decision-support prototype for academic research.',
    goodMorning: 'Good morning, Kasun 👋',
    katugasthota: 'Katugasthota DEC',
    notificationTitle: 'Notifications',
    todaySales: 'Today\'s Sales',
    currentStock: 'Current Stock',
    forecastDemand: 'Forecast Demand',
    estimatedWaste: 'Estimated Waste',
    atRiskItems: 'At-Risk Items',
    dashboardSubtitle: 'What is happening with my stock today?',
    healthyStock: 'Healthy Stock',
    attentionNeeded: 'Attention Needed',
    critical: 'Critical',
    inventoryHealth: 'Today\'s Inventory Health',
    smartInsight: 'Smart Insight',
    viewForecast: 'View Forecast',
    viewRecommendation: 'View Recommendation',
    inventorySearch: 'Search vegetables',
    filterAll: 'All',
    filterHealthy: 'Healthy',
    filterAttention: 'Attention',
    filterCritical: 'Critical',
    recordStock: 'Record Stock',
    vegetable: 'Vegetable',
    openingStock: 'Opening Stock',
    received: 'Received',
    sold: 'Sold',
    currentStockLabel: 'Current Stock',
    forecastDemandLabel: 'Forecast Demand',
    status: 'Status',
    recommendation: 'Recommendation',
    addStock: 'Add stock record',
    quantity: 'Quantity',
    type: 'Type',
    date: 'Date',
    save: 'Save',
    close: 'Close',
    todaySalesPage: 'Today\'s sales',
    weeklySales: 'Weekly sales',
    monthlySales: 'Monthly sales',
    salesTrend: 'Sales trend',
    vegetablePerformance: 'Vegetable performance',
    quantitySold: 'Quantity Sold',
    revenue: 'Revenue',
    trend: 'Trend',
    demandForecast: 'Demand Forecast',
    forecastSubtitle: 'Estimated demand for the next 7 days',
    historicalDemand: 'Historical Demand',
    forecastDemandChart: 'Forecast Demand',
    forecastSummary: 'Forecast Summary',
    next3Days: 'Next 3 Days',
    next7Days: 'Next 7 Days',
    forecastReliability: 'Forecast Reliability',
    whatInfluenced: 'What influenced this forecast?',
    recentSales: 'Recent Sales',
    recentPrice: 'Recent Price',
    weather: 'Weather',
    seasonalPattern: 'Seasonal Pattern',
    whyRecommendation: 'Why this recommendation?',
    smartInventoryRecommendations: 'Smart Inventory Recommendations',
    recommendationSubtitle: 'Simple actions based on expected demand and current stock.',
    currentStockShort: 'Current stock',
    expectedDemandShort: 'Expected demand',
    recommendedPurchase: 'Recommended purchase',
    why: 'Why?',
    acceptRecommendation: 'Accept Recommendation',
    viewDetails: 'View Details',
    noPurchaseRequired: 'No Purchase Required',
    maintainCurrentStock: 'Maintain current stock.',
    highRisk: 'High Risk',
    bufferView: 'Inventory Buffer View',
    redZone: 'RED ZONE',
    yellowZone: 'YELLOW ZONE',
    greenZone: 'GREEN ZONE',
    criticalStock: 'Critical stock',
    replenishmentRequired: 'Replenishment required',
    healthyStockZone: 'Healthy stock',
    totalWaste: 'Total Waste',
    wasteRate: 'Waste Rate',
    estimatedLoss: 'Estimated Loss',
    mainWasteContributors: 'Main Waste Contributors',
    sampleValues: 'Sample/demo values only',
    generateReport: 'Generate Report',
    reportGenerated: 'Report generated successfully.',
    profile: 'Profile',
    businessInformation: 'Business Information',
    language: 'Language',
    notifications: 'Notifications',
    systemPreferences: 'System Preferences',
    businessName: 'Business Name',
    economicCentre: 'Economic Centre',
    contact: 'Contact',
    preferredUnit: 'Preferred Unit',
    saveChanges: 'Save Changes',
    kg: 'kg',
    units: 'units',
    noSalesData: 'No sales data available yet.',
    noSalesHint: 'Start recording daily sales to generate demand forecasts.',
    addSalesRecord: 'Add Sales Record',
    noForecast: 'No forecast available',
    noForecastHint: 'More historical data is required before generating a reliable prediction.',
    unableToLoad: 'Unable to load inventory data.',
    retry: 'Retry',
    invalidQuantity: 'Please enter a valid quantity.',
    deleteRecord: 'Delete record?',
    deleteWarning: 'This action cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    all: 'All',
    healthy: 'Healthy',
    attention: 'Attention',
    filter: 'Filter',
    confirm: 'Confirm',
    aiAssisted: 'AI Assisted',
    recommendedPurchaseLabel: 'Recommended purchase:',
    reasonLabel: 'Reason:',
    stockSaved: 'Stock record saved successfully.',
    inventoryRefreshed: 'Inventory refreshed.',
    salesAdded: 'Sales record added.',
    settingsSaved: 'Settings saved.',
    recommendationAccepted: 'Recommendation accepted for review.',
    sampleValue: 'Sample value',
    prototypeOnly: 'Prototype only',
    good: 'Good',
    fromYesterday: '↑ 8.4% from yesterday',
    aboveLastWeek: '3.2% above last week',
    basedOnSales: 'Based on recent sales',
    needsReview: 'Needs review today',
    insightText: 'Carrot demand is expected to increase by approximately 18% over the next 3 days.',
    insightReason: 'Recent sales increased and upcoming demand is higher than the current stock level.',
    wasteByVegetable: 'Waste by vegetable',
    generatePracticalSummary: 'Generate practical summaries for daily decision-making.',
    updatePreferences: 'Update operational preferences and seller profile details.',
    lowStockAlerts: 'Low stock alerts',
    weatherTitle: 'Weather',
    salesAndPrice: 'Sales and price trend',
    viewDetailsTitle: 'View details',
    strongWeek: 'Strong week',
    stableGrowth: 'Stable growth',
    checkConnection: 'Please check your connection and try again.'
  },
  si: {
    loginTitle: 'දත්ත-මත පදනම් වූ ඉල්ලුම් අනුමානය සමඟ සූක්ෂම මිලදී ගත් තීරණ ගන්න.',
    loginKicker: 'පිළිගනිමු',
    signInTitle: 'පිවිසෙන්න',
    usernameLabel: 'පරිශීලක නාමය හෝ ඊමේල්',
    passwordLabel: 'මුරපදය',
    rememberMe: 'මතක තබන්න',
    loginButton: 'පිවිසෙන්න',
    demoAccount: 'ඩිමෝ ගිණුම',
    tagline: 'පළතුරු අපද්‍රව්‍ය අඩු කිරීම',
    dashboard: 'උපකරණ පුවරුව',
    inventory: 'තොග කළමනාකරණය',
    sales: 'විකුණුම්',
    forecast: 'ඉල්ලුම් අනුමානය',
    recommendations: 'නිර්දේශ',
    waste: 'අපද්‍රව්‍ය',
    reports: 'වාර්තා',
    settings: 'සැකසුම්',
    prototypeVersion: 'ප්‍රෝටෝටයිප් අනුවාදය 0.1',
    prototypeNote: 'අධ්‍යයන පර්යේෂණය සඳහා තීරණ-සහායක ප්‍රෝටෝටයිප්.',
    goodMorning: 'සුබ උදෑසනක්, කසුන් 👋',
    katugasthota: 'කටුගස්තොට ඩීඊසී',
    notificationTitle: 'දැනුම්දීම්',
    todaySales: 'අද විකුණුම්',
    currentStock: 'වර්තමාන තොගය',
    forecastDemand: 'අනුමාන ඉල්ලුම',
    estimatedWaste: 'ඇස්තමේන්තුගත අපද්‍රව්‍ය',
    atRiskItems: 'අවදානම් අයිතම',
    dashboardSubtitle: 'අද මගේ තොගයේ තත්වය කුමක්ද?',
    healthyStock: 'සෞඛ්‍යමත් තොගය',
    attentionNeeded: 'අවධානය අවශ්‍යයි',
    critical: 'ගැටළු සහිත',
    inventoryHealth: 'අද තොගයේ තත්ත්වය',
    smartInsight: 'ස්මාර්ට් දෘෂ්ටි කෝණය',
    viewForecast: 'අනුමානය බලන්න',
    viewRecommendation: 'නිර්දේශය බලන්න',
    inventorySearch: 'පළතුරු සොයන්න',
    filterAll: 'සියල්ල',
    filterHealthy: 'සෞඛ්‍යමත්',
    filterAttention: 'අවධානය',
    filterCritical: 'ගැටළු සහිත',
    recordStock: 'තොග වාර්තාවක් එක් කරන්න',
    vegetable: 'පළතුරු',
    openingStock: 'ආරම්භක තොගය',
    received: 'ලැබුණි',
    sold: 'විකුණා',
    currentStockLabel: 'වර්තමාන තොගය',
    forecastDemandLabel: 'අනුමාන ඉල්ලුම',
    status: 'තත්ත්වය',
    recommendation: 'නිර්දේශය',
    addStock: 'තොග වාර්තාවක් එක් කරන්න',
    quantity: 'ප්‍රමාණය',
    type: 'වර්ගය',
    date: 'දිනය',
    save: 'සුරකින්න',
    close: 'වසන්න',
    todaySalesPage: 'අද විකුණුම්',
    weeklySales: 'සතියේ විකුණුම්',
    monthlySales: 'මාසයේ විකුණුම්',
    salesTrend: 'විකුණුම් ප්‍රවණතාව',
    vegetablePerformance: 'පළතුරු කාර්ය සාධනය',
    quantitySold: 'විකුණූ ප්‍රමාණය',
    revenue: 'ආදායම',
    trend: 'ප්‍රවණතාව',
    demandForecast: 'ඉල්ලුම් අනුමානය',
    forecastSubtitle: 'ඊළඟ දින 7 සඳහා ඇස්තමේන්තු කළ ඉල්ලුම',
    historicalDemand: 'ඓතිහාසික ඉල්ලුම',
    forecastDemandChart: 'අනුමාන ඉල්ලුම',
    forecastSummary: 'අනුමාන සාරාංශය',
    next3Days: 'ඊළඟ දින 3',
    next7Days: 'ඊළඟ දින 7',
    forecastReliability: 'අනුමාන විශ්වාසය',
    whatInfluenced: 'මෙම අනුමානයට කුමන සාධක බලපා තිබුණේද?',
    recentSales: 'මෑත විකුණුම්',
    recentPrice: 'මෑත මිල',
    weather: 'කාළගුණය',
    seasonalPattern: 'සෘතුමය රටාව',
    whyRecommendation: 'මෙම නිර්දේශය සකස් වන්නේ ඇයි?',
    smartInventoryRecommendations: 'ස්මාර්ට් තොග නිර්දේශ',
    recommendationSubtitle: 'අපේක්ෂිත ඉල්ලුමට සහ වර්තමාන තොගයට අනුව ගත් සරල ක්‍රියාමාර්ග.',
    currentStockShort: 'වර්තමාන තොගය',
    expectedDemandShort: 'අපේක්ෂිත ඉල්ලුම',
    recommendedPurchase: 'නිර්දේශිත මිලදී ගැනීම',
    why: 'කාරණය',
    acceptRecommendation: 'නිර්දේශය පිළිගන්න',
    viewDetails: 'විස්තර බලන්න',
    noPurchaseRequired: 'මිලදී ගැනීම අවශ්‍ය නැත',
    maintainCurrentStock: 'වර්තමාන තොගය පවත්වා ගන්න.',
    highRisk: 'අධි අවදානම්',
    bufferView: 'තොග බෆර් දසුන',
    redZone: 'රතු කලාපය',
    yellowZone: 'කහ කලාපය',
    greenZone: 'කොළ කලාපය',
    criticalStock: 'අවදානම් තොගය',
    replenishmentRequired: 'ප්‍රතිපූරණය අවශ්‍යයි',
    healthyStockZone: 'සෞඛ්‍යමත් තොගය',
    totalWaste: 'සම්පූර්ණ අපද්‍රව්‍ය',
    wasteRate: 'අපද්‍රව්‍ය අනුපාතය',
    estimatedLoss: 'ඇස්තමේන්තුගත හානිය',
    mainWasteContributors: 'ප්‍රධාන අපද්‍රව්‍ය දායකයින්',
    sampleValues: 'උදාහරණ/ප්‍රදර්ශන අගයන් පමණි',
    generateReport: 'වාර්තාව ජනනය කරන්න',
    reportGenerated: 'වාර්තාව සාර්ථකව ජනනය විය.',
    profile: 'පැතිකඩ',
    businessInformation: 'ව්‍යාපාර තොරතුරු',
    language: 'භාෂාව',
    notifications: 'දැනුම්දීම්',
    systemPreferences: 'පද්ධති අභිමත',
    businessName: 'ව්‍යාපාර නාමය',
    economicCentre: 'අර්ථික මධ්‍යස්ථානය',
    contact: 'සම්බන්ධතාව',
    preferredUnit: 'කැමති ඒකකය',
    saveChanges: 'වෙනස්කම් සුරකින්න',
    kg: 'කිලෝග්‍රෑම්',
    units: 'ඒකක',
    noSalesData: 'තවම විකුණුම් දත්ත නොමැත.',
    noSalesHint: 'දෛනික විකුණුම් වාර්තා කිරීමෙන් ඉල්ලුම් අනුමානයක් සෑදිය හැක.',
    addSalesRecord: 'විකුණුම් වාර්තාව එක් කරන්න',
    noForecast: 'අනුමානයක් නොමැත',
    noForecastHint: 'විශ්වාසදායක අනුමානයක් සෑදීමට තවත් historical දත්ත අවශ්‍ය වේ.',
    unableToLoad: 'තොග දත්ත පූරණය කළ නොහැකි විය.',
    retry: 'නැවත උත්සාහ කරන්න',
    invalidQuantity: 'වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න.',
    deleteRecord: 'වාර්තාව මකන්නද?',
    deleteWarning: 'මෙම ක්‍රියාව ප්‍රතිවර්තනය කළ නොහැක.',
    cancel: 'අවලංගු කරන්න',
    delete: 'මකන්න',
    all: 'සියල්ල',
    healthy: 'සෞඛ්‍යමත්',
    attention: 'අවධානය',
    filter: 'පෙරහන්',
    confirm: 'තහවුරු කරන්න',
    aiAssisted: 'AI සහායක',
    recommendedPurchaseLabel: 'නිර්දේශිත මිලදී ගැනීම:',
    reasonLabel: 'හේතුව:',
    stockSaved: 'තොග වාර්තාව සාර්ථකව සුරකින ලදී.',
    inventoryRefreshed: 'තොග දත්ත නැවුම් කරන ලදී.',
    salesAdded: 'විකුණුම් වාර්තාව එක් කරන ලදී.',
    settingsSaved: 'සැකසුම් සුරකින ලදී.',
    recommendationAccepted: 'නිර්දේශය සමාලෝචනයට පිළිගැනුණි.',
    sampleValue: 'උදාහරණ අගය',
    prototypeOnly: 'ප්‍රෝටෝටයිප් පමණි',
    good: 'හොඳය',
    fromYesterday: '↑ 8.4% පසු දිනට වඩා',
    aboveLastWeek: '3.2% පසු සතියට වඩා වැඩි',
    basedOnSales: 'මෑත විකුණුම් මත පදනම්ව',
    needsReview: 'අද අත්‍යවශ්‍ය පරීක්ෂාව',
    insightText: 'කාර්ට් එකේ ඉල්ලුම ඉදිරියෙන් දින 3 කට වඩා ආසන්නව 18% කින් වැඩි වනු ඇති.',
    insightReason: 'මෑත විකුණුම් වැඩි වී ඇති අතර ඉදිරියේ ඉල්ලුම වර්තමාන තොගයට වඩා වැඩි බව පෙනේ.',
    wasteByVegetable: 'පළතුරු අනුව අපද්‍රව්‍ය',
    generatePracticalSummary: 'දෛනික තීරණ සඳහා ප්‍රායෝගික සාරාංශ ජනනය කරන්න.',
    updatePreferences: 'ක්‍රියාකාරී අභිමත සහ විකුණුම්කරුවෙකුගේ පැතිකඩ යාවත්කාලීන කරන්න.',
    lowStockAlerts: 'අඩු තොග අනතුරු ඇඟවීම්',
    weatherTitle: 'කාළගුණය',
    salesAndPrice: 'විකුණුම් හා මිල ප්‍රවණතාව',
    viewDetailsTitle: 'විස්තර බලන්න',
    strongWeek: 'ශක්තිමත් සතිය',
    stableGrowth: 'ස්ථායී වර්ධනය',
    checkConnection: 'අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කර නැවත උත්සාහ කරන්න.'
  }
};

window.translations = translations;
